language: node_js
node_js:
  - "0.8"
before_install: npm install -g grunt-cli
install: npm install
before_script: grunt build


language: node_js
node_js:
  - "iojs"

deploy:
  provider: s3
  access_key_id: ""
  secret_access_key: ""
  bucket: "S3 Bucket"
  skip_cleanup: true
  region: "Bucket region"
